name: comply
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  http: ^1.2.1
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.4
  image_picker: ^1.0.8
  location: ^5.0.0

  # Added missing packages
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/splashlogo.jpg"
  image_path_ios: "assets/images/splashlogo.jpg"
  adaptive_icon_background: "#00000000"
  adaptive_icon_foreground: "assets/images/splashlogo.jpg"
  min_sdk_android: 21

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splashlogo.jpg
    - assets/images/logo.jpg
    - assets/images/logologo.jpg
    - assets/images/hotel.jpg
    - assets/images/hotel1.jpg
    - assets/images/worker.jpg
    - assets/images/onboarding.jpg
    - assets/images/ru.jpg
    - assets/images/uz.jpg
    - assets/images/en.jpg
